spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/devops_dashboard}
    username: ${DB_USERNAME:devops}
    password: ${DB_PASSWORD:devops123}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 8081
